
[[brazil2020]]
    name = "Detalhes do Evento"
    url = "/2020/brazil/#plan-of-the-day"
    weight = 1
    
[[brazil2020]]
    name = "Palestrantes"
    url = "/2020/brazil/#speakers"
    weight = 2

[[brazil2020]]
    name = "Participe"
    weight = 3

[[brazil2020]]
    name = "Código de Conduta"
    url = "/2020/brazil/code-of-conduct/"
    weight = 1
    parent = "Participe"
    
[[brazil2020]]
    name = "Termo de Compromisso"
    url = "/2020/brazil/speaker-agreement/"
    weight = 2
    parent = "Participe"



[[portuguese2021]]
    name = "Detalhes do Evento"
    url = "/2021/portuguese/#plan-of-the-day"
    weight = 1
    
[[portuguese2021]]
    name = "Palestrantes"
    url = "/2021/portuguese/#speakers"
    weight = 2

[[portuguese2021]]
    name = "Participe"
    weight = 3

[[portuguese2021]]
    name = "Código de Conduta"
    url = "/2021/portuguese/code-of-conduct/"
    weight = 1
    parent = "Participe"
    
[[portuguese2021]]
    name = "Termo de Compromisso"
    url = "/2021/portuguese/speaker-agreement/"
    weight = 2
    parent = "Participe"
